version: '3.7'

services:
  fhir:
    container_name: ${CONTAINER_NAME1}
    image: "hapiproject/hapi:latest"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
    depends_on:
      - db
  db:
    container_name: ${CONTAINER_NAME2}
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    volumes:
      - ./postgress.data:/var/lib/postgresql/data

configs:
  hapi:
     file: ./hapi.application.yaml